### ISSUE TITLE
Unable to locate package install.bash

### ISSUE THREAD

**Issue by TrkMstr25** [wahlmanj/HomebridgeOSXscripts#1]
Hi,

I'm trying to install the install.bash as sudo but I'm stuck. This is the code:

```pi@raspberrypi:~ $ sudo apt-get install install.bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package install.bash
E: Couldn't find any package by regex 'install.bash'
pi@raspberrypi:~ $ ```

Any help please?

Thanks.

**Comment by wahlmanj** [comment]
You need to clone the git or download the .zip.

**Comment by TrkMstr25** [comment]
@wahlmanj I downloaded it but I don't know how to run it. I also searched online for the command but it's no clear to me how to run the install.bash. Could you please tell me how? Thanks.
